Dec 22 06:50:40 cloud-init[2561]: util.py[DEBUG]: Cloud-init v. 19.3-3.amzn2 running 'init-local' at Tue, 22 Dec 2020 06:50:40 +0000. Up 8.96 seconds.
Dec 22 06:50:40 cloud-init[2561]: main.py[DEBUG]: No kernel command line url found.
Dec 22 06:50:40 cloud-init[2561]: main.py[DEBUG]: Closing stdin.
Dec 22 06:50:40 cloud-init[2561]: util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [644] 0 bytes
Dec 22 06:50:40 cloud-init[2561]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance/boot-finished
Dec 22 06:50:40 cloud-init[2561]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/data/no-net
Dec 22 06:50:40 cloud-init[2561]: handlers.py[DEBUG]: start: init-local/check-cache: attempting to read from cache [check]
Dec 22 06:50:40 cloud-init[2561]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
Dec 22 06:50:40 cloud-init[2561]: stages.py[DEBUG]: no cache found
Dec 22 06:50:40 cloud-init[2561]: handlers.py[DEBUG]: finish: init-local/check-cache: SUCCESS: no cache found
Dec 22 06:50:40 cloud-init[2561]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
Dec 22 06:50:40 cloud-init[2561]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Dec 22 06:50:40 cloud-init[2561]: __init__.py[DEBUG]: Looking for data source in: ['Ec2', 'None'], via packages ['', u'cloudinit.sources'] that matches dependencies ['FILESYSTEM']
Dec 22 06:50:40 cloud-init[2561]: __init__.py[DEBUG]: Searching for local data source in: []
Dec 22 06:50:40 cloud-init[2561]: main.py[DEBUG]: No local datasource found
Dec 22 06:50:40 cloud-init[2561]: util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)
Dec 22 06:50:40 cloud-init[2561]: util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address
Dec 22 06:50:40 cloud-init[2561]: util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
Dec 22 06:50:40 cloud-init[2561]: util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
Dec 22 06:50:40 cloud-init[2561]: stages.py[DEBUG]: network config disabled by system_cfg
Dec 22 06:50:40 cloud-init[2561]: stages.py[INFO]: network config is disabled by system_cfg
Dec 22 06:50:40 cloud-init[2561]: main.py[DEBUG]: [local] Exiting without datasource
Dec 22 06:50:40 cloud-init[2561]: atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmptd9Aip) - w: [644] 489 bytes/chars
Dec 22 06:50:40 cloud-init[2561]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
Dec 22 06:50:40 cloud-init[2561]: util.py[DEBUG]: Read 11 bytes from /proc/uptime
Dec 22 06:50:40 cloud-init[2561]: util.py[DEBUG]: cloud-init mode 'init' took 0.119 seconds (0.12)
Dec 22 06:50:40 cloud-init[2561]: handlers.py[DEBUG]: finish: init-local: SUCCESS: searching for local datasources
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Cloud-init v. 19.3-3.amzn2 running 'init' at Tue, 22 Dec 2020 06:51:17 +0000. Up 45.51 seconds.
Dec 22 06:51:17 cloud-init[2900]: main.py[DEBUG]: No kernel command line url found.
Dec 22 06:51:17 cloud-init[2900]: main.py[DEBUG]: Closing stdin.
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [644] 0 bytes
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Running command ['ip', 'addr', 'show'] with allowed return codes [0] (shell=False, capture=True)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Running command ['ip', '-o', 'route', 'list'] with allowed return codes [0] (shell=False, capture=True)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Running command ['ip', '--oneline', '-6', 'route', 'list', 'table', 'all'] with allowed return codes [0, 1] (shell=False, capture=True)
Dec 22 06:51:17 cloud-init[2900]: main.py[DEBUG]: Checking to see if files that we need already exist from a previous run that would allow us to stop early.
Dec 22 06:51:17 cloud-init[2900]: main.py[DEBUG]: Execution continuing, no previous run detected that would allow us to stop early.
Dec 22 06:51:17 cloud-init[2900]: handlers.py[DEBUG]: start: init-network/check-cache: attempting to read from cache [trust]
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: stages.py[DEBUG]: no cache found
Dec 22 06:51:17 cloud-init[2900]: handlers.py[DEBUG]: finish: init-network/check-cache: SUCCESS: no cache found
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
Dec 22 06:51:17 cloud-init[2900]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Dec 22 06:51:17 cloud-init[2900]: __init__.py[DEBUG]: Looking for data source in: ['Ec2', 'None'], via packages ['', u'cloudinit.sources'] that matches dependencies ['FILESYSTEM', 'NETWORK']
Dec 22 06:51:17 cloud-init[2900]: __init__.py[DEBUG]: Searching for network data source in: [u'DataSourceEc2', u'DataSourceNone']
Dec 22 06:51:17 cloud-init[2900]: handlers.py[DEBUG]: start: init-network/search-Ec2: searching for network data from DataSourceEc2
Dec 22 06:51:17 cloud-init[2900]: __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceEc2.DataSourceEc2'>
Dec 22 06:51:17 cloud-init[2900]: __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /sys/hypervisor/uuid (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Read 37 bytes from /sys/hypervisor/uuid
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Read 0 bytes from /proc/1/environ
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Read 1298 bytes from /proc/self/status
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_serial
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /sys/class/dmi/id/product_serial (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Read 37 bytes from /sys/class/dmi/id/product_serial
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: dmi data /sys/class/dmi/id/product_serial returned ec2e0238-4cd6-e55d-653a-27cda6c5bf1a
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Read 0 bytes from /proc/1/environ
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Read 1298 bytes from /proc/self/status
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: querying dmi data /sys/class/dmi/id/chassis_asset_tag
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /sys/class/dmi/id/chassis_asset_tag (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Read 1 bytes from /sys/class/dmi/id/chassis_asset_tag
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: dmi data /sys/class/dmi/id/chassis_asset_tag returned 
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Read 0 bytes from /proc/1/environ
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Read 1298 bytes from /proc/self/status
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: querying dmi data /sys/class/dmi/id/sys_vendor
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /sys/class/dmi/id/sys_vendor (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Read 4 bytes from /sys/class/dmi/id/sys_vendor
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: dmi data /sys/class/dmi/id/sys_vendor returned Xen
Dec 22 06:51:17 cloud-init[2900]: DataSourceEc2.py[DEBUG]: strict_mode: warn, cloud_name=aws cloud_platform=ec2
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Resolving URL: http://169.254.169.254 took 0.006 seconds
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Resolving URL: http://instance-data.:8773 took 0.002 seconds
Dec 22 06:51:17 cloud-init[2900]: DataSourceEc2.py[DEBUG]: Removed the following from metadata urls: ['http://instance-data.:8773']
Dec 22 06:51:17 cloud-init[2900]: DataSourceEc2.py[DEBUG]: Fetching Ec2 IMDSv2 API Token
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254/latest/api/token' with {'url': 'http://169.254.169.254/latest/api/token', 'headers': {'X-aws-ec2-metadata-token-ttl-seconds': '21600', 'User-Agent': 'Cloud-Init/19.3-3.amzn2'}, 'allow_redirects': True, 'method': 'PUT', 'timeout': 1.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/api/token (200, 56b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: DataSourceEc2.py[DEBUG]: Using metadata source: 'http://169.254.169.254'
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254/2016-09-02/meta-data/instance-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/instance-id', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q==', 'User-Agent': 'Cloud-Init/19.3-3.amzn2'}, 'allow_redirects': True, 'method': 'GET'} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/instance-id (200, 19b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: DataSourceEc2.py[DEBUG]: Found preferred metadata version 2016-09-02
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/user-data' with {'url': 'http://169.254.169.254/2016-09-02/user-data', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/user-data (200, 1976b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/ (200, 263b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ (200, 8b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ami' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ami', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ami (200, 9b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/root' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/root', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/root (200, 9b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/metrics/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/metrics/', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/metrics/ (200, 7b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/metrics/vhostmd' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/metrics/vhostmd', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/metrics/vhostmd (200, 38b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/ (200, 11b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/ (200, 5b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/ (200, 18b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/ (200, 230b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/ipv4-associations/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/ipv4-associations/', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/ipv4-associations/ (200, 11b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/ipv4-associations/65.0.177.66' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/ipv4-associations/65.0.177.66', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/ipv4-associations/65.0.177.66 (200, 9b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/local-hostname' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/local-hostname', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/local-hostname (200, 40b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/security-groups' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/security-groups', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/security-groups (200, 48b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/public-hostname' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/public-hostname', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/public-hostname (200, 48b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/vpc-ipv4-cidr-blocks' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/vpc-ipv4-cidr-blocks', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/vpc-ipv4-cidr-blocks (200, 11b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/subnet-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/subnet-id', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/subnet-id (200, 24b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/public-ipv4s' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/public-ipv4s', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/public-ipv4s (200, 11b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/interface-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/interface-id', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/interface-id (200, 21b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/mac' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/mac', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/mac (200, 17b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/security-group-ids' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/security-group-ids', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/security-group-ids (200, 20b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/vpc-ipv4-cidr-block' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/vpc-ipv4-cidr-block', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/vpc-ipv4-cidr-block (200, 11b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/local-ipv4s' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/local-ipv4s', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/local-ipv4s (200, 9b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/owner-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/owner-id', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/owner-id (200, 12b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/subnet-ipv4-cidr-block' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/subnet-ipv4-cidr-block', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/subnet-ipv4-cidr-block (200, 11b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/device-number' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/device-number', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/device-number (200, 1b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/vpc-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/vpc-id', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/0a:93:d7:fb:1e:bc/vpc-id (200, 21b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/placement/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/placement/', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/placement/ (200, 17b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/placement/availability-zone' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/placement/availability-zone', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/placement/availability-zone (200, 11b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/public-keys/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/public-keys/', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/public-keys/ (200, 9b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/public-keys/0/openssh-key' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/public-keys/0/openssh-key', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/public-keys/0/openssh-key (200, 389b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/services/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/services/', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/services/ (200, 16b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/services/domain' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/services/domain', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/services/domain (200, 13b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/services/partition' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/services/partition', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/services/partition (200, 3b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/profile' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/profile', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/profile (200, 11b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/local-ipv4' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/local-ipv4', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/local-ipv4 (200, 9b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/reservation-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/reservation-id', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/reservation-id (200, 19b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/local-hostname' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/local-hostname', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/local-hostname (200, 40b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/security-groups' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/security-groups', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/security-groups (200, 48b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/ami-launch-index' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/ami-launch-index', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/ami-launch-index (200, 1b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/public-hostname' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/public-hostname', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/public-hostname (200, 48b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/hostname' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/hostname', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/hostname (200, 40b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/ami-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/ami-id', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/ami-id (200, 21b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/instance-action' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/instance-action', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/instance-action (200, 4b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/mac' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/mac', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/mac (200, 17b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/public-ipv4' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/public-ipv4', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/public-ipv4 (200, 11b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/ami-manifest-path' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/ami-manifest-path', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/ami-manifest-path (200, 9b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/instance-type' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/instance-type', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/instance-type (200, 9b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/instance-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/instance-id', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/instance-id (200, 19b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/dynamic/instance-identity' with {'url': 'http://169.254.169.254/2016-09-02/dynamic/instance-identity', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/dynamic/instance-identity (200, 33b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/document' with {'url': 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/document', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/dynamic/instance-identity/document (200, 476b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/rsa2048' with {'url': 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/rsa2048', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/dynamic/instance-identity/rsa2048 (200, 1434b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/pkcs7' with {'url': 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/pkcs7', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/dynamic/instance-identity/pkcs7 (200, 1118b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/signature' with {'url': 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/signature', 'headers': {'X-aws-ec2-metadata-token': 'AQAAACxXnytl3VlDvCdv4jSA5b1vVnq605QGf2V2Rx2N7MXBf9yp2Q=='}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 22 06:51:17 cloud-init[2900]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/dynamic/instance-identity/signature (200, 174b) after 1 attempts
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Crawl of metadata service took 0.367 seconds
Dec 22 06:51:17 cloud-init[2900]: atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data.json (via temporary file /run/cloud-init/tmppDPyXE) - w: [644] 7197 bytes/chars
Dec 22 06:51:17 cloud-init[2900]: atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data-sensitive.json (via temporary file /run/cloud-init/tmpDt3W9Z) - w: [600] 7197 bytes/chars
Dec 22 06:51:17 cloud-init[2900]: handlers.py[DEBUG]: finish: init-network/search-Ec2: SUCCESS: found network data from DataSourceEc2
Dec 22 06:51:17 cloud-init[2900]: stages.py[INFO]: Loaded datasource DataSourceEc2 - DataSourceEc2
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Read 1585 bytes from /etc/cloud/cloud.cfg
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Attempting to load yaml from string of length 1585 with allowed root types (<type 'dict'>,)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Read 590 bytes from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Attempting to load yaml from string of length 590 with allowed root types (<type 'dict'>,)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Read 2106 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Attempting to load yaml from string of length 2106 with allowed root types (<type 'dict'>,)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<type 'dict'>,)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: loaded blob returned None, returning default.
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/i-04e01e659767335ea'
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /var/lib/cloud/instances/i-04e01e659767335ea/datasource (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04e01e659767335ea/datasource - wb: [644] 29 bytes
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 29 bytes
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: stages.py[DEBUG]: previous iid found to be NO_PREVIOUS_INSTANCE_ID
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 20 bytes
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 20 bytes
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 24 bytes
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 13914 bytes
Dec 22 06:51:17 cloud-init[2900]: main.py[DEBUG]: [net] init will now be targeting instance id: i-04e01e659767335ea. new=True
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Read 1585 bytes from /etc/cloud/cloud.cfg
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Attempting to load yaml from string of length 1585 with allowed root types (<type 'dict'>,)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Read 590 bytes from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Attempting to load yaml from string of length 590 with allowed root types (<type 'dict'>,)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Read 2106 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Attempting to load yaml from string of length 2106 with allowed root types (<type 'dict'>,)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<type 'dict'>,)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: loaded blob returned None, returning default.
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
Dec 22 06:51:17 cloud-init[2900]: __init__.py[DEBUG]: Stable ifnames disabled by net.ifnames=0 in /proc/cmdline
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /sys/class/net/eth0/carrier (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Read 2 bytes from /sys/class/net/eth0/carrier
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address
Dec 22 06:51:17 cloud-init[2900]: stages.py[DEBUG]: network config disabled by system_cfg
Dec 22 06:51:17 cloud-init[2900]: stages.py[INFO]: network config is disabled by system_cfg
Dec 22 06:51:17 cloud-init[2900]: handlers.py[DEBUG]: start: init-network/setup-datasource: setting up datasource
Dec 22 06:51:17 cloud-init[2900]: handlers.py[DEBUG]: finish: init-network/setup-datasource: SUCCESS: setting up datasource
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04e01e659767335ea/user-data.txt - wb: [600] 1976 bytes
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04e01e659767335ea/user-data.txt.i - wb: [600] 2319 bytes
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04e01e659767335ea/vendor-data.txt - wb: [600] 0 bytes
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04e01e659767335ea/vendor-data.txt.i - wb: [600] 345 bytes
Dec 22 06:51:17 cloud-init[2900]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Dec 22 06:51:17 cloud-init[2900]: cc_set_hostname.py[DEBUG]: Setting the hostname to ip-10-0-0-22.ap-south-1.compute.internal (ip-10-0-0-22)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Running command ['hostnamectl', 'set-hostname', 'ip-10-0-0-22.ap-south-1.compute.internal'] with allowed return codes [0] (shell=False, capture=True)
Dec 22 06:51:17 cloud-init[2900]: __init__.py[DEBUG]: Non-persistently setting the system hostname to ip-10-0-0-22.ap-south-1.compute.internal
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Running command ['hostname', 'ip-10-0-0-22.ap-south-1.compute.internal'] with allowed return codes [0] (shell=False, capture=True)
Dec 22 06:51:17 cloud-init[2900]: atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/set-hostname (via temporary file /var/lib/cloud/data/tmpPP46WI) - w: [644] 86 bytes/chars
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04e01e659767335ea/sem/consume_data - wb: [644] 20 bytes
Dec 22 06:51:17 cloud-init[2900]: helpers.py[DEBUG]: Running consume_data using lock (<FileLock using file '/var/lib/cloud/instances/i-04e01e659767335ea/sem/consume_data'>)
Dec 22 06:51:17 cloud-init[2900]: handlers.py[DEBUG]: start: init-network/consume-user-data: reading and applying user-data
Dec 22 06:51:17 cloud-init[2900]: launch_index.py[DEBUG]: Discarding 0 multipart messages which do not match launch index 0
Dec 22 06:51:17 cloud-init[2900]: stages.py[DEBUG]: Added default handler for set(['text/cloud-config-jsonp', 'text/cloud-config']) from CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']]
Dec 22 06:51:17 cloud-init[2900]: stages.py[DEBUG]: Added default handler for set(['text/x-shellscript']) from ShellScriptPartHandler: [['text/x-shellscript']]
Dec 22 06:51:17 cloud-init[2900]: stages.py[DEBUG]: Added default handler for set(['text/cloud-boothook']) from BootHookPartHandler: [['text/cloud-boothook']]
Dec 22 06:51:17 cloud-init[2900]: stages.py[DEBUG]: Added default handler for set(['text/upstart-job']) from UpstartJobPartHandler: [['text/upstart-job']]
Dec 22 06:51:17 cloud-init[2900]: stages.py[DEBUG]: Added default handler for set(['text/jinja2']) from JinjaTemplatePartHandler: [['text/jinja2']]
Dec 22 06:51:17 cloud-init[2900]: __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__begin__, None, 3) with frequency once-per-instance
Dec 22 06:51:17 cloud-init[2900]: __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__begin__, None, 2) with frequency once-per-instance
Dec 22 06:51:17 cloud-init[2900]: __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__begin__, None, 2) with frequency once-per-instance
Dec 22 06:51:17 cloud-init[2900]: __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__begin__, None, 3) with frequency once-per-instance
Dec 22 06:51:17 cloud-init[2900]: __init__.py[DEBUG]: Calling handler UpstartJobPartHandler: [['text/upstart-job']] (__begin__, None, 2) with frequency once-per-instance
Dec 22 06:51:17 cloud-init[2900]: __init__.py[DEBUG]: {'Content-Type': 'text/x-shellscript', 'Content-Disposition': 'attachment; filename="part-001"', 'MIME-Version': '1.0'}
Dec 22 06:51:17 cloud-init[2900]: __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (text/x-shellscript, part-001, 2) with frequency once-per-instance
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Writing to /var/lib/cloud/instance/scripts/part-001 - wb: [700] 1976 bytes
Dec 22 06:51:17 cloud-init[2900]: __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__end__, None, 3) with frequency once-per-instance
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04e01e659767335ea/cloud-config.txt - wb: [600] 0 bytes
Dec 22 06:51:17 cloud-init[2900]: __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__end__, None, 2) with frequency once-per-instance
Dec 22 06:51:17 cloud-init[2900]: __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__end__, None, 2) with frequency once-per-instance
Dec 22 06:51:17 cloud-init[2900]: __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__end__, None, 3) with frequency once-per-instance
Dec 22 06:51:17 cloud-init[2900]: __init__.py[DEBUG]: Calling handler UpstartJobPartHandler: [['text/upstart-job']] (__end__, None, 2) with frequency once-per-instance
Dec 22 06:51:17 cloud-init[2900]: handlers.py[DEBUG]: finish: init-network/consume-user-data: SUCCESS: reading and applying user-data
Dec 22 06:51:17 cloud-init[2900]: handlers.py[DEBUG]: start: init-network/consume-vendor-data: reading and applying vendor-data
Dec 22 06:51:17 cloud-init[2900]: stages.py[DEBUG]: no vendordata from datasource
Dec 22 06:51:17 cloud-init[2900]: handlers.py[DEBUG]: finish: init-network/consume-vendor-data: SUCCESS: reading and applying vendor-data
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Read 1585 bytes from /etc/cloud/cloud.cfg
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Attempting to load yaml from string of length 1585 with allowed root types (<type 'dict'>,)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Read 590 bytes from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Attempting to load yaml from string of length 590 with allowed root types (<type 'dict'>,)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Read 2106 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Attempting to load yaml from string of length 2106 with allowed root types (<type 'dict'>,)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<type 'dict'>,)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: loaded blob returned None, returning default.
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Read 0 bytes from /var/lib/cloud/instance/cloud-config.txt
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<type 'dict'>,)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: loaded blob returned None, returning default.
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Read 0 bytes from /var/lib/cloud/instance/cloud-config.txt
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<type 'dict'>,)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: loaded blob returned None, returning default.
Dec 22 06:51:17 cloud-init[2900]: handlers.py[DEBUG]: start: init-network/activate-datasource: activating datasource
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 15830 bytes
Dec 22 06:51:17 cloud-init[2900]: handlers.py[DEBUG]: finish: init-network/activate-datasource: SUCCESS: activating datasource
Dec 22 06:51:17 cloud-init[2900]: main.py[DEBUG]: no di_report found in config.
Dec 22 06:51:17 cloud-init[2900]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Dec 22 06:51:17 cloud-init[2900]: stages.py[DEBUG]: Running module migrator (<module 'cloudinit.config.cc_migrator' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_migrator.pyc'>) with frequency always
Dec 22 06:51:17 cloud-init[2900]: handlers.py[DEBUG]: start: init-network/config-migrator: running config-migrator with frequency always
Dec 22 06:51:17 cloud-init[2900]: helpers.py[DEBUG]: Running config-migrator using lock (<cloudinit.helpers.DummyLock object at 0x7fa6eb7cf250>)
Dec 22 06:51:17 cloud-init[2900]: cc_migrator.py[DEBUG]: Migrated 0 semaphore files to there canonicalized names
Dec 22 06:51:17 cloud-init[2900]: handlers.py[DEBUG]: finish: init-network/config-migrator: SUCCESS: config-migrator ran successfully
Dec 22 06:51:17 cloud-init[2900]: stages.py[DEBUG]: Running module bootcmd (<module 'cloudinit.config.cc_bootcmd' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_bootcmd.pyc'>) with frequency always
Dec 22 06:51:17 cloud-init[2900]: handlers.py[DEBUG]: start: init-network/config-bootcmd: running config-bootcmd with frequency always
Dec 22 06:51:17 cloud-init[2900]: helpers.py[DEBUG]: Running config-bootcmd using lock (<cloudinit.helpers.DummyLock object at 0x7fa6eb7cf6d0>)
Dec 22 06:51:17 cloud-init[2900]: cc_bootcmd.py[DEBUG]: Skipping module named bootcmd, no 'bootcmd' key in configuration
Dec 22 06:51:17 cloud-init[2900]: handlers.py[DEBUG]: finish: init-network/config-bootcmd: SUCCESS: config-bootcmd ran successfully
Dec 22 06:51:17 cloud-init[2900]: stages.py[DEBUG]: Running module write-files (<module 'cloudinit.config.cc_write_files' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_write_files.pyc'>) with frequency once-per-instance
Dec 22 06:51:17 cloud-init[2900]: handlers.py[DEBUG]: start: init-network/config-write-files: running config-write-files with frequency once-per-instance
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04e01e659767335ea/sem/config_write_files - wb: [644] 20 bytes
Dec 22 06:51:17 cloud-init[2900]: helpers.py[DEBUG]: Running config-write-files using lock (<FileLock using file '/var/lib/cloud/instances/i-04e01e659767335ea/sem/config_write_files'>)
Dec 22 06:51:17 cloud-init[2900]: cc_write_files.py[DEBUG]: Skipping module named write-files, no/empty 'write_files' key in configuration
Dec 22 06:51:17 cloud-init[2900]: handlers.py[DEBUG]: finish: init-network/config-write-files: SUCCESS: config-write-files ran successfully
Dec 22 06:51:17 cloud-init[2900]: stages.py[DEBUG]: Running module write-metadata (<module 'cloudinit.config.cc_write_metadata' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_write_metadata.pyc'>) with frequency once-per-instance
Dec 22 06:51:17 cloud-init[2900]: handlers.py[DEBUG]: start: init-network/config-write-metadata: running config-write-metadata with frequency once-per-instance
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04e01e659767335ea/sem/config_write_metadata - wb: [644] 20 bytes
Dec 22 06:51:17 cloud-init[2900]: helpers.py[DEBUG]: Running config-write-metadata using lock (<FileLock using file '/var/lib/cloud/instances/i-04e01e659767335ea/sem/config_write_metadata'>)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Writing to /etc/yum/vars/awsregion - wb: [644] 10 bytes
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Changing the ownership of /etc/yum/vars/awsregion to 0:0
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Writing to /etc/yum/vars/awsdomain - wb: [644] 13 bytes
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Changing the ownership of /etc/yum/vars/awsdomain to 0:0
Dec 22 06:51:17 cloud-init[2900]: handlers.py[DEBUG]: finish: init-network/config-write-metadata: SUCCESS: config-write-metadata ran successfully
Dec 22 06:51:17 cloud-init[2900]: stages.py[DEBUG]: Running module growpart (<module 'cloudinit.config.cc_growpart' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_growpart.pyc'>) with frequency always
Dec 22 06:51:17 cloud-init[2900]: handlers.py[DEBUG]: start: init-network/config-growpart: running config-growpart with frequency always
Dec 22 06:51:17 cloud-init[2900]: helpers.py[DEBUG]: Running config-growpart using lock (<cloudinit.helpers.DummyLock object at 0x7fa6ecd7d5d0>)
Dec 22 06:51:17 cloud-init[2900]: cc_growpart.py[DEBUG]: No 'growpart' entry in cfg.  Using default: {'ignore_growroot_disabled': False, 'mode': 'auto', 'devices': ['/']}
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Running command ['growpart', '--help'] with allowed return codes [0] (shell=False, capture=True)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /proc/2900/mountinfo (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Read 2532 bytes from /proc/2900/mountinfo
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Read 0 bytes from /proc/1/environ
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Read 1299 bytes from /proc/self/status
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /etc/os-release (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Read 212 bytes from /etc/os-release
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /sys/class/block/xvda1/partition (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Read 2 bytes from /sys/class/block/xvda1/partition
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /sys/devices/vbd-51712/block/xvda/dev (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Read 6 bytes from /sys/devices/vbd-51712/block/xvda/dev
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Running command ['growpart', '--dry-run', '/dev/xvda', '1'] with allowed return codes [0] (shell=False, capture=True)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: resize_devices took 0.055 seconds
Dec 22 06:51:17 cloud-init[2900]: cc_growpart.py[DEBUG]: '/' NOCHANGE: no change necessary (/dev/xvda, 1)
Dec 22 06:51:17 cloud-init[2900]: handlers.py[DEBUG]: finish: init-network/config-growpart: SUCCESS: config-growpart ran successfully
Dec 22 06:51:17 cloud-init[2900]: stages.py[DEBUG]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_resizefs.pyc'>) with frequency always
Dec 22 06:51:17 cloud-init[2900]: handlers.py[DEBUG]: start: init-network/config-resizefs: running config-resizefs with frequency always
Dec 22 06:51:17 cloud-init[2900]: helpers.py[DEBUG]: Running config-resizefs using lock (<cloudinit.helpers.DummyLock object at 0x7fa6ecda3090>)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /proc/2900/mountinfo (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Read 2532 bytes from /proc/2900/mountinfo
Dec 22 06:51:17 cloud-init[2900]: cc_resizefs.py[DEBUG]: resize_info: dev=/dev/xvda1 mnt_point=/ path=/
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Read 0 bytes from /proc/1/environ
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Read 1299 bytes from /proc/self/status
Dec 22 06:51:17 cloud-init[2900]: cc_resizefs.py[DEBUG]: Resizing / (xfs) using xfs_growfs /
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Forked child 3038 who will run callback log_time
Dec 22 06:51:17 cloud-init[2900]: cc_resizefs.py[DEBUG]: Resizing (via forking) root filesystem (type=xfs, val=noblock)
Dec 22 06:51:17 cloud-init[3038]: util.py[DEBUG]: Running command ('xfs_growfs', '/') with allowed return codes [0] (shell=False, capture=True)
Dec 22 06:51:17 cloud-init[2900]: handlers.py[DEBUG]: finish: init-network/config-resizefs: SUCCESS: config-resizefs ran successfully
Dec 22 06:51:17 cloud-init[2900]: stages.py[DEBUG]: Running module set-hostname (<module 'cloudinit.config.cc_set_hostname' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_set_hostname.pyc'>) with frequency once-per-instance
Dec 22 06:51:17 cloud-init[2900]: handlers.py[DEBUG]: start: init-network/config-set-hostname: running config-set-hostname with frequency once-per-instance
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04e01e659767335ea/sem/config_set_hostname - wb: [644] 20 bytes
Dec 22 06:51:17 cloud-init[2900]: helpers.py[DEBUG]: Running config-set-hostname using lock (<FileLock using file '/var/lib/cloud/instances/i-04e01e659767335ea/sem/config_set_hostname'>)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /var/lib/cloud/data/set-hostname (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Read 86 bytes from /var/lib/cloud/data/set-hostname
Dec 22 06:51:17 cloud-init[2900]: cc_set_hostname.py[DEBUG]: No hostname changes. Skipping set-hostname
Dec 22 06:51:17 cloud-init[2900]: handlers.py[DEBUG]: finish: init-network/config-set-hostname: SUCCESS: config-set-hostname ran successfully
Dec 22 06:51:17 cloud-init[2900]: stages.py[DEBUG]: Running module update-hostname (<module 'cloudinit.config.cc_update_hostname' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_update_hostname.pyc'>) with frequency always
Dec 22 06:51:17 cloud-init[2900]: handlers.py[DEBUG]: start: init-network/config-update-hostname: running config-update-hostname with frequency always
Dec 22 06:51:17 cloud-init[2900]: helpers.py[DEBUG]: Running config-update-hostname using lock (<cloudinit.helpers.DummyLock object at 0x7fa6eb6d46d0>)
Dec 22 06:51:17 cloud-init[2900]: cc_update_hostname.py[DEBUG]: Updating hostname to ip-10-0-0-22.ap-south-1.compute.internal (ip-10-0-0-22)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Running command ['hostname'] with allowed return codes [0] (shell=False, capture=True)
Dec 22 06:51:17 cloud-init[2900]: __init__.py[DEBUG]: Attempting to update hostname to ip-10-0-0-22.ap-south-1.compute.internal in 1 files
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-hostname - wb: [644] 40 bytes
Dec 22 06:51:17 cloud-init[2900]: handlers.py[DEBUG]: finish: init-network/config-update-hostname: SUCCESS: config-update-hostname ran successfully
Dec 22 06:51:17 cloud-init[2900]: stages.py[DEBUG]: Running module update-etc-hosts (<module 'cloudinit.config.cc_update_etc_hosts' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_update_etc_hosts.pyc'>) with frequency always
Dec 22 06:51:17 cloud-init[2900]: handlers.py[DEBUG]: start: init-network/config-update-etc-hosts: running config-update-etc-hosts with frequency always
Dec 22 06:51:17 cloud-init[3038]: util.py[DEBUG]: backgrounded Resizing took 0.008 seconds
Dec 22 06:51:17 cloud-init[2900]: helpers.py[DEBUG]: Running config-update-etc-hosts using lock (<cloudinit.helpers.DummyLock object at 0x7fa6eb6d4610>)
Dec 22 06:51:17 cloud-init[2900]: cc_update_etc_hosts.py[DEBUG]: Configuration option 'manage_etc_hosts' is not set, not managing /etc/hosts in module update-etc-hosts
Dec 22 06:51:17 cloud-init[2900]: handlers.py[DEBUG]: finish: init-network/config-update-etc-hosts: SUCCESS: config-update-etc-hosts ran successfully
Dec 22 06:51:17 cloud-init[2900]: stages.py[DEBUG]: Running module rsyslog (<module 'cloudinit.config.cc_rsyslog' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_rsyslog.pyc'>) with frequency once-per-instance
Dec 22 06:51:17 cloud-init[2900]: handlers.py[DEBUG]: start: init-network/config-rsyslog: running config-rsyslog with frequency once-per-instance
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04e01e659767335ea/sem/config_rsyslog - wb: [644] 20 bytes
Dec 22 06:51:17 cloud-init[2900]: helpers.py[DEBUG]: Running config-rsyslog using lock (<FileLock using file '/var/lib/cloud/instances/i-04e01e659767335ea/sem/config_rsyslog'>)
Dec 22 06:51:17 cloud-init[2900]: cc_rsyslog.py[DEBUG]: Skipping module named rsyslog, no 'rsyslog' key in configuration
Dec 22 06:51:17 cloud-init[2900]: handlers.py[DEBUG]: finish: init-network/config-rsyslog: SUCCESS: config-rsyslog ran successfully
Dec 22 06:51:17 cloud-init[2900]: stages.py[DEBUG]: Running module users-groups (<module 'cloudinit.config.cc_users_groups' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_users_groups.pyc'>) with frequency once-per-instance
Dec 22 06:51:17 cloud-init[2900]: handlers.py[DEBUG]: start: init-network/config-users-groups: running config-users-groups with frequency once-per-instance
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04e01e659767335ea/sem/config_users_groups - wb: [644] 20 bytes
Dec 22 06:51:17 cloud-init[2900]: helpers.py[DEBUG]: Running config-users-groups using lock (<FileLock using file '/var/lib/cloud/instances/i-04e01e659767335ea/sem/config_users_groups'>)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /etc/os-release (quiet=True)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Read 212 bytes from /etc/os-release
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /etc/system-image/channel.ini (quiet=True)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Read 0 bytes from /etc/system-image/channel.ini
Dec 22 06:51:17 cloud-init[2900]: __init__.py[DEBUG]: Adding user ec2-user
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Running hidden command to protect sensitive input/output logstring: ['useradd', 'ec2-user', '--comment', 'EC2 Default User', '--groups', 'adm,systemd-journal,wheel', '--shell', '/bin/bash', '-m']
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Running command ['passwd', '-l', 'ec2-user'] with allowed return codes [0] (shell=False, capture=True)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /etc/sudoers (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Read 4328 bytes from /etc/sudoers
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Writing to /etc/sudoers.d/90-cloud-init-users - wb: [440] 134 bytes
Dec 22 06:51:17 cloud-init[2900]: handlers.py[DEBUG]: finish: init-network/config-users-groups: SUCCESS: config-users-groups ran successfully
Dec 22 06:51:17 cloud-init[2900]: stages.py[DEBUG]: Running module ssh (<module 'cloudinit.config.cc_ssh' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_ssh.pyc'>) with frequency once-per-instance
Dec 22 06:51:17 cloud-init[2900]: handlers.py[DEBUG]: start: init-network/config-ssh: running config-ssh with frequency once-per-instance
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04e01e659767335ea/sem/config_ssh - wb: [644] 19 bytes
Dec 22 06:51:17 cloud-init[2900]: helpers.py[DEBUG]: Running config-ssh using lock (<FileLock using file '/var/lib/cloud/instances/i-04e01e659767335ea/sem/config_ssh'>)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh to 1000:1000
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Read 3958 bytes from /etc/ssh/sshd_config
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Writing to /home/ec2-user/.ssh/authorized_keys - wb: [600] 389 bytes
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh/authorized_keys to 1000:1000
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Changing the ownership of /root/.ssh to 0:0
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Read 3958 bytes from /etc/ssh/sshd_config
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 546 bytes
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Changing the ownership of /root/.ssh/authorized_keys to 0:0
Dec 22 06:51:17 cloud-init[2900]: handlers.py[DEBUG]: finish: init-network/config-ssh: SUCCESS: config-ssh ran successfully
Dec 22 06:51:17 cloud-init[2900]: stages.py[DEBUG]: Running module resolv-conf (<module 'cloudinit.config.cc_resolv_conf' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_resolv_conf.pyc'>) with frequency once-per-instance
Dec 22 06:51:17 cloud-init[2900]: handlers.py[DEBUG]: start: init-network/config-resolv-conf: running config-resolv-conf with frequency once-per-instance
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04e01e659767335ea/sem/config_resolv_conf - wb: [644] 20 bytes
Dec 22 06:51:17 cloud-init[2900]: helpers.py[DEBUG]: Running config-resolv-conf using lock (<FileLock using file '/var/lib/cloud/instances/i-04e01e659767335ea/sem/config_resolv_conf'>)
Dec 22 06:51:17 cloud-init[2900]: cc_resolv_conf.py[DEBUG]: Skipping module named resolv-conf, no 'manage_resolv_conf' key in configuration
Dec 22 06:51:17 cloud-init[2900]: handlers.py[DEBUG]: finish: init-network/config-resolv-conf: SUCCESS: config-resolv-conf ran successfully
Dec 22 06:51:17 cloud-init[2900]: main.py[DEBUG]: Ran 13 modules with 0 failures
Dec 22 06:51:17 cloud-init[2900]: atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmp1jU2N4) - w: [644] 526 bytes/chars
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: Read 12 bytes from /proc/uptime
Dec 22 06:51:17 cloud-init[2900]: util.py[DEBUG]: cloud-init mode 'init' took 0.787 seconds (0.79)
Dec 22 06:51:17 cloud-init[2900]: handlers.py[DEBUG]: finish: init-network: SUCCESS: searching for network datasources
Dec 22 06:51:18 cloud-init[3052]: util.py[DEBUG]: Cloud-init v. 19.3-3.amzn2 running 'modules:config' at Tue, 22 Dec 2020 06:51:18 +0000. Up 46.79 seconds.
Dec 22 06:51:18 cloud-init[3052]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Dec 22 06:51:18 cloud-init[3052]: stages.py[DEBUG]: Running module disk_setup (<module 'cloudinit.config.cc_disk_setup' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_disk_setup.pyc'>) with frequency once-per-instance
Dec 22 06:51:18 cloud-init[3052]: handlers.py[DEBUG]: start: modules-config/config-disk_setup: running config-disk_setup with frequency once-per-instance
Dec 22 06:51:18 cloud-init[3052]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04e01e659767335ea/sem/config_disk_setup - wb: [644] 19 bytes
Dec 22 06:51:18 cloud-init[3052]: helpers.py[DEBUG]: Running config-disk_setup using lock (<FileLock using file '/var/lib/cloud/instances/i-04e01e659767335ea/sem/config_disk_setup'>)
Dec 22 06:51:18 cloud-init[3052]: handlers.py[DEBUG]: finish: modules-config/config-disk_setup: SUCCESS: config-disk_setup ran successfully
Dec 22 06:51:18 cloud-init[3052]: stages.py[DEBUG]: Running module mounts (<module 'cloudinit.config.cc_mounts' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_mounts.pyc'>) with frequency once-per-instance
Dec 22 06:51:18 cloud-init[3052]: handlers.py[DEBUG]: start: modules-config/config-mounts: running config-mounts with frequency once-per-instance
Dec 22 06:51:18 cloud-init[3052]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04e01e659767335ea/sem/config_mounts - wb: [644] 20 bytes
Dec 22 06:51:18 cloud-init[3052]: helpers.py[DEBUG]: Running config-mounts using lock (<FileLock using file '/var/lib/cloud/instances/i-04e01e659767335ea/sem/config_mounts'>)
Dec 22 06:51:18 cloud-init[3052]: cc_mounts.py[DEBUG]: mounts configuration is [['ephemeral0', '/media/ephemeral0'], ['swap', 'none', 'swap', 'sw', '0', '0']]
Dec 22 06:51:18 cloud-init[3052]: util.py[DEBUG]: Reading from /etc/fstab (quiet=False)
Dec 22 06:51:18 cloud-init[3052]: util.py[DEBUG]: Read 91 bytes from /etc/fstab
Dec 22 06:51:18 cloud-init[3052]: cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0
Dec 22 06:51:18 cloud-init[3052]: DataSourceEc2.py[DEBUG]: Unable to convert ephemeral0 to a device
Dec 22 06:51:18 cloud-init[3052]: cc_mounts.py[DEBUG]: changed ephemeral0 => None
Dec 22 06:51:18 cloud-init[3052]: cc_mounts.py[DEBUG]: Ignoring nonexistent named mount ephemeral0
Dec 22 06:51:18 cloud-init[3052]: cc_mounts.py[DEBUG]: Attempting to determine the real name of swap
Dec 22 06:51:18 cloud-init[3052]: DataSourceEc2.py[DEBUG]: Unable to convert swap to a device
Dec 22 06:51:18 cloud-init[3052]: cc_mounts.py[DEBUG]: changed swap => None
Dec 22 06:51:18 cloud-init[3052]: cc_mounts.py[DEBUG]: Ignoring nonexistent named mount swap
Dec 22 06:51:18 cloud-init[3052]: cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0
Dec 22 06:51:18 cloud-init[3052]: DataSourceEc2.py[DEBUG]: Unable to convert ephemeral0 to a device
Dec 22 06:51:18 cloud-init[3052]: cc_mounts.py[DEBUG]: changed default device ephemeral0 => None
Dec 22 06:51:18 cloud-init[3052]: cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount ephemeral0
Dec 22 06:51:18 cloud-init[3052]: cc_mounts.py[DEBUG]: Attempting to determine the real name of swap
Dec 22 06:51:18 cloud-init[3052]: DataSourceEc2.py[DEBUG]: Unable to convert swap to a device
Dec 22 06:51:18 cloud-init[3052]: cc_mounts.py[DEBUG]: changed default device swap => None
Dec 22 06:51:18 cloud-init[3052]: cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount swap
Dec 22 06:51:18 cloud-init[3052]: cc_mounts.py[DEBUG]: Skipping nonexistent device named None
Dec 22 06:51:18 cloud-init[3052]: cc_mounts.py[DEBUG]: Skipping nonexistent device named None
Dec 22 06:51:18 cloud-init[3052]: cc_mounts.py[DEBUG]: no need to setup swap
Dec 22 06:51:18 cloud-init[3052]: cc_mounts.py[DEBUG]: No modifications to fstab needed
Dec 22 06:51:18 cloud-init[3052]: handlers.py[DEBUG]: finish: modules-config/config-mounts: SUCCESS: config-mounts ran successfully
Dec 22 06:51:18 cloud-init[3052]: stages.py[DEBUG]: Running module locale (<module 'cloudinit.config.cc_locale' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_locale.pyc'>) with frequency once-per-instance
Dec 22 06:51:18 cloud-init[3052]: handlers.py[DEBUG]: start: modules-config/config-locale: running config-locale with frequency once-per-instance
Dec 22 06:51:18 cloud-init[3052]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04e01e659767335ea/sem/config_locale - wb: [644] 20 bytes
Dec 22 06:51:18 cloud-init[3052]: helpers.py[DEBUG]: Running config-locale using lock (<FileLock using file '/var/lib/cloud/instances/i-04e01e659767335ea/sem/config_locale'>)
Dec 22 06:51:18 cloud-init[3052]: cc_locale.py[DEBUG]: Setting locale to en_US.UTF-8
Dec 22 06:51:18 cloud-init[3052]: util.py[DEBUG]: Reading from /etc/locale.conf (quiet=False)
Dec 22 06:51:18 cloud-init[3052]: util.py[DEBUG]: Writing to /etc/locale.conf - wb: [644] 92 bytes
Dec 22 06:51:18 cloud-init[3052]: handlers.py[DEBUG]: finish: modules-config/config-locale: SUCCESS: config-locale ran successfully
Dec 22 06:51:18 cloud-init[3052]: stages.py[DEBUG]: Running module set-passwords (<module 'cloudinit.config.cc_set_passwords' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_set_passwords.pyc'>) with frequency once-per-instance
Dec 22 06:51:18 cloud-init[3052]: handlers.py[DEBUG]: start: modules-config/config-set-passwords: running config-set-passwords with frequency once-per-instance
Dec 22 06:51:18 cloud-init[3052]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04e01e659767335ea/sem/config_set_passwords - wb: [644] 20 bytes
Dec 22 06:51:18 cloud-init[3052]: helpers.py[DEBUG]: Running config-set-passwords using lock (<FileLock using file '/var/lib/cloud/instances/i-04e01e659767335ea/sem/config_set_passwords'>)
Dec 22 06:51:18 cloud-init[3052]: util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
Dec 22 06:51:18 cloud-init[3052]: util.py[DEBUG]: Read 3958 bytes from /etc/ssh/sshd_config
Dec 22 06:51:18 cloud-init[3052]: ssh_util.py[DEBUG]: line 63: option PasswordAuthentication updated yes -> no
Dec 22 06:51:18 cloud-init[3052]: util.py[DEBUG]: Writing to /etc/ssh/sshd_config - wb: [600] 3957 bytes
Dec 22 06:51:18 cloud-init[3052]: util.py[DEBUG]: Running command ['service', 'sshd', 'restart'] with allowed return codes [0] (shell=False, capture=True)
Dec 22 06:51:18 cloud-init[3052]: cc_set_passwords.py[DEBUG]: Restarted the ssh daemon.
Dec 22 06:51:18 cloud-init[3052]: handlers.py[DEBUG]: finish: modules-config/config-set-passwords: SUCCESS: config-set-passwords ran successfully
Dec 22 06:51:18 cloud-init[3052]: stages.py[DEBUG]: Running module yum-configure (<module 'cloudinit.config.cc_yum_configure' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_yum_configure.pyc'>) with frequency once-per-instance
Dec 22 06:51:18 cloud-init[3052]: handlers.py[DEBUG]: start: modules-config/config-yum-configure: running config-yum-configure with frequency once-per-instance
Dec 22 06:51:18 cloud-init[3052]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04e01e659767335ea/sem/config_yum_configure - wb: [644] 20 bytes
Dec 22 06:51:18 cloud-init[3052]: helpers.py[DEBUG]: Running config-yum-configure using lock (<FileLock using file '/var/lib/cloud/instances/i-04e01e659767335ea/sem/config_yum_configure'>)
Dec 22 06:51:18 cloud-init[3052]: cc_yum_configure.py[DEBUG]: Generating default repo files
Dec 22 06:51:18 cloud-init[3052]: __init__.py[DEBUG]: filtered distro mirror info: {}
Dec 22 06:51:18 cloud-init[3052]: cc_yum_configure.py[DEBUG]: mirror_info: {}
Dec 22 06:51:18 cloud-init[3052]: cc_yum_configure.py[DEBUG]: No mirror info found; ignoring.
Dec 22 06:51:18 cloud-init[3052]: cc_yum_configure.py[INFO]: No releasever provided, leaving yum.conf unchanged.
Dec 22 06:51:18 cloud-init[3052]: cc_yum_configure.py[INFO]: No repo target provided, leaving target unchanged.
Dec 22 06:51:18 cloud-init[3052]: handlers.py[DEBUG]: finish: modules-config/config-yum-configure: SUCCESS: config-yum-configure ran successfully
Dec 22 06:51:18 cloud-init[3052]: stages.py[DEBUG]: Running module yum-add-repo (<module 'cloudinit.config.cc_yum_add_repo' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_yum_add_repo.pyc'>) with frequency once-per-instance
Dec 22 06:51:18 cloud-init[3052]: handlers.py[DEBUG]: start: modules-config/config-yum-add-repo: running config-yum-add-repo with frequency once-per-instance
Dec 22 06:51:18 cloud-init[3052]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04e01e659767335ea/sem/config_yum_add_repo - wb: [644] 20 bytes
Dec 22 06:51:18 cloud-init[3052]: helpers.py[DEBUG]: Running config-yum-add-repo using lock (<FileLock using file '/var/lib/cloud/instances/i-04e01e659767335ea/sem/config_yum_add_repo'>)
Dec 22 06:51:18 cloud-init[3052]: cc_yum_add_repo.py[DEBUG]: Skipping module named yum-add-repo, no 'yum_repos' configuration found
Dec 22 06:51:18 cloud-init[3052]: handlers.py[DEBUG]: finish: modules-config/config-yum-add-repo: SUCCESS: config-yum-add-repo ran successfully
Dec 22 06:51:18 cloud-init[3052]: stages.py[DEBUG]: Running module package-update-upgrade-install (<module 'cloudinit.config.cc_package_update_upgrade_install' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_package_update_upgrade_install.pyc'>) with frequency once-per-instance
Dec 22 06:51:18 cloud-init[3052]: handlers.py[DEBUG]: start: modules-config/config-package-update-upgrade-install: running config-package-update-upgrade-install with frequency once-per-instance
Dec 22 06:51:18 cloud-init[3052]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04e01e659767335ea/sem/config_package_update_upgrade_install - wb: [644] 20 bytes
Dec 22 06:51:18 cloud-init[3052]: helpers.py[DEBUG]: Running config-package-update-upgrade-install using lock (<FileLock using file '/var/lib/cloud/instances/i-04e01e659767335ea/sem/config_package_update_upgrade_install'>)
Dec 22 06:51:18 cloud-init[3052]: amazon.py[DEBUG]: Upgrade level: security
Dec 22 06:51:18 cloud-init[3052]: rhel.py[DEBUG]: Using YUM for package management
Dec 22 06:51:18 cloud-init[3052]: util.py[DEBUG]: Running command ['yum', '-t', '-y', '--exclude=kernel', '--exclude=nvidia*', '--exclude=cuda*', '--security', '--sec-severity=critical', '--sec-severity=important', 'upgrade'] with allowed return codes [0] (shell=False, capture=False)
Dec 22 06:51:33 cloud-init[3052]: handlers.py[DEBUG]: finish: modules-config/config-package-update-upgrade-install: SUCCESS: config-package-update-upgrade-install ran successfully
Dec 22 06:51:33 cloud-init[3052]: stages.py[DEBUG]: Running module timezone (<module 'cloudinit.config.cc_timezone' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_timezone.pyc'>) with frequency once-per-instance
Dec 22 06:51:33 cloud-init[3052]: handlers.py[DEBUG]: start: modules-config/config-timezone: running config-timezone with frequency once-per-instance
Dec 22 06:51:33 cloud-init[3052]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04e01e659767335ea/sem/config_timezone - wb: [644] 20 bytes
Dec 22 06:51:33 cloud-init[3052]: helpers.py[DEBUG]: Running config-timezone using lock (<FileLock using file '/var/lib/cloud/instances/i-04e01e659767335ea/sem/config_timezone'>)
Dec 22 06:51:33 cloud-init[3052]: cc_timezone.py[DEBUG]: Skipping module named timezone, no 'timezone' specified
Dec 22 06:51:33 cloud-init[3052]: handlers.py[DEBUG]: finish: modules-config/config-timezone: SUCCESS: config-timezone ran successfully
Dec 22 06:51:33 cloud-init[3052]: stages.py[DEBUG]: Running module disable-ec2-metadata (<module 'cloudinit.config.cc_disable_ec2_metadata' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_disable_ec2_metadata.pyc'>) with frequency always
Dec 22 06:51:33 cloud-init[3052]: handlers.py[DEBUG]: start: modules-config/config-disable-ec2-metadata: running config-disable-ec2-metadata with frequency always
Dec 22 06:51:33 cloud-init[3052]: helpers.py[DEBUG]: Running config-disable-ec2-metadata using lock (<cloudinit.helpers.DummyLock object at 0x7fb15e0df710>)
Dec 22 06:51:33 cloud-init[3052]: cc_disable_ec2_metadata.py[DEBUG]: Skipping module named disable-ec2-metadata, disabling the ec2 route not enabled
Dec 22 06:51:33 cloud-init[3052]: handlers.py[DEBUG]: finish: modules-config/config-disable-ec2-metadata: SUCCESS: config-disable-ec2-metadata ran successfully
Dec 22 06:51:33 cloud-init[3052]: stages.py[DEBUG]: Running module runcmd (<module 'cloudinit.config.cc_runcmd' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_runcmd.pyc'>) with frequency once-per-instance
Dec 22 06:51:33 cloud-init[3052]: handlers.py[DEBUG]: start: modules-config/config-runcmd: running config-runcmd with frequency once-per-instance
Dec 22 06:51:33 cloud-init[3052]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04e01e659767335ea/sem/config_runcmd - wb: [644] 20 bytes
Dec 22 06:51:33 cloud-init[3052]: helpers.py[DEBUG]: Running config-runcmd using lock (<FileLock using file '/var/lib/cloud/instances/i-04e01e659767335ea/sem/config_runcmd'>)
Dec 22 06:51:33 cloud-init[3052]: cc_runcmd.py[DEBUG]: Skipping module named runcmd, no 'runcmd' key in configuration
Dec 22 06:51:33 cloud-init[3052]: handlers.py[DEBUG]: finish: modules-config/config-runcmd: SUCCESS: config-runcmd ran successfully
Dec 22 06:51:33 cloud-init[3052]: main.py[DEBUG]: Ran 10 modules with 0 failures
Dec 22 06:51:33 cloud-init[3052]: atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpgAfInq) - w: [644] 552 bytes/chars
Dec 22 06:51:33 cloud-init[3052]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
Dec 22 06:51:33 cloud-init[3052]: util.py[DEBUG]: Read 12 bytes from /proc/uptime
Dec 22 06:51:33 cloud-init[3052]: util.py[DEBUG]: cloud-init mode 'modules' took 15.560 seconds (15.56)
Dec 22 06:51:33 cloud-init[3052]: handlers.py[DEBUG]: finish: modules-config: SUCCESS: running modules for config
Dec 22 06:51:34 cloud-init[3276]: util.py[DEBUG]: Cloud-init v. 19.3-3.amzn2 running 'modules:final' at Tue, 22 Dec 2020 06:51:34 +0000. Up 62.73 seconds.
Dec 22 06:51:34 cloud-init[3276]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Dec 22 06:51:34 cloud-init[3276]: stages.py[DEBUG]: Running module scripts-per-once (<module 'cloudinit.config.cc_scripts_per_once' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_per_once.pyc'>) with frequency once
Dec 22 06:51:34 cloud-init[3276]: handlers.py[DEBUG]: start: modules-final/config-scripts-per-once: running config-scripts-per-once with frequency once
Dec 22 06:51:34 cloud-init[3276]: util.py[DEBUG]: Writing to /var/lib/cloud/sem/config_scripts_per_once.once - wb: [644] 20 bytes
Dec 22 06:51:34 cloud-init[3276]: helpers.py[DEBUG]: Running config-scripts-per-once using lock (<FileLock using file '/var/lib/cloud/sem/config_scripts_per_once.once'>)
Dec 22 06:51:34 cloud-init[3276]: handlers.py[DEBUG]: finish: modules-final/config-scripts-per-once: SUCCESS: config-scripts-per-once ran successfully
Dec 22 06:51:34 cloud-init[3276]: stages.py[DEBUG]: Running module scripts-per-boot (<module 'cloudinit.config.cc_scripts_per_boot' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_per_boot.pyc'>) with frequency always
Dec 22 06:51:34 cloud-init[3276]: handlers.py[DEBUG]: start: modules-final/config-scripts-per-boot: running config-scripts-per-boot with frequency always
Dec 22 06:51:34 cloud-init[3276]: helpers.py[DEBUG]: Running config-scripts-per-boot using lock (<cloudinit.helpers.DummyLock object at 0x7f88899539d0>)
Dec 22 06:51:34 cloud-init[3276]: handlers.py[DEBUG]: finish: modules-final/config-scripts-per-boot: SUCCESS: config-scripts-per-boot ran successfully
Dec 22 06:51:34 cloud-init[3276]: stages.py[DEBUG]: Running module scripts-per-instance (<module 'cloudinit.config.cc_scripts_per_instance' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_per_instance.pyc'>) with frequency once-per-instance
Dec 22 06:51:34 cloud-init[3276]: handlers.py[DEBUG]: start: modules-final/config-scripts-per-instance: running config-scripts-per-instance with frequency once-per-instance
Dec 22 06:51:34 cloud-init[3276]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04e01e659767335ea/sem/config_scripts_per_instance - wb: [644] 20 bytes
Dec 22 06:51:34 cloud-init[3276]: helpers.py[DEBUG]: Running config-scripts-per-instance using lock (<FileLock using file '/var/lib/cloud/instances/i-04e01e659767335ea/sem/config_scripts_per_instance'>)
Dec 22 06:51:34 cloud-init[3276]: handlers.py[DEBUG]: finish: modules-final/config-scripts-per-instance: SUCCESS: config-scripts-per-instance ran successfully
Dec 22 06:51:34 cloud-init[3276]: stages.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.pyc'>) with frequency once-per-instance
Dec 22 06:51:34 cloud-init[3276]: handlers.py[DEBUG]: start: modules-final/config-scripts-user: running config-scripts-user with frequency once-per-instance
Dec 22 06:51:34 cloud-init[3276]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04e01e659767335ea/sem/config_scripts_user - wb: [644] 20 bytes
Dec 22 06:51:34 cloud-init[3276]: helpers.py[DEBUG]: Running config-scripts-user using lock (<FileLock using file '/var/lib/cloud/instances/i-04e01e659767335ea/sem/config_scripts_user'>)
Dec 22 06:51:34 cloud-init[3276]: util.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/part-001'] with allowed return codes [0] (shell=True, capture=False)
Dec 22 06:53:35 cloud-init[3276]: util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/part-001 [1]
Dec 22 06:53:35 cloud-init[3276]: util.py[DEBUG]: Failed running /var/lib/cloud/instance/scripts/part-001 [1]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cloudinit/util.py", line 910, in runparts
    subp(prefix + [exe_path], capture=False, shell=True)
  File "/usr/lib/python2.7/site-packages/cloudinit/util.py", line 2105, in subp
    cmd=args)
ProcessExecutionError: Unexpected error while running command.
Command: ['/var/lib/cloud/instance/scripts/part-001']
Exit code: 1
Reason: -
Stdout: -
Stderr: -
Dec 22 06:53:35 cloud-init[3276]: cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
Dec 22 06:53:35 cloud-init[3276]: handlers.py[DEBUG]: finish: modules-final/config-scripts-user: FAIL: running config-scripts-user with frequency once-per-instance
Dec 22 06:53:35 cloud-init[3276]: util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.pyc'>) failed
Dec 22 06:53:35 cloud-init[3276]: util.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.pyc'>) failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cloudinit/stages.py", line 851, in _run_modules
    freq=freq)
  File "/usr/lib/python2.7/site-packages/cloudinit/cloud.py", line 54, in run
    return self._runners.run(name, functor, args, freq, clear_on_fail)
  File "/usr/lib/python2.7/site-packages/cloudinit/helpers.py", line 187, in run
    results = functor(*args)
  File "/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.py", line 45, in handle
    util.runparts(runparts_path)
  File "/usr/lib/python2.7/site-packages/cloudinit/util.py", line 917, in runparts
    % (len(failed), len(attempted)))
RuntimeError: Runparts: 1 failures in 1 attempted commands
Dec 22 06:53:35 cloud-init[3276]: stages.py[DEBUG]: Running module ssh-authkey-fingerprints (<module 'cloudinit.config.cc_ssh_authkey_fingerprints' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_ssh_authkey_fingerprints.pyc'>) with frequency once-per-instance
Dec 22 06:53:35 cloud-init[3276]: handlers.py[DEBUG]: start: modules-final/config-ssh-authkey-fingerprints: running config-ssh-authkey-fingerprints with frequency once-per-instance
Dec 22 06:53:35 cloud-init[3276]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04e01e659767335ea/sem/config_ssh_authkey_fingerprints - wb: [644] 20 bytes
Dec 22 06:53:35 cloud-init[3276]: helpers.py[DEBUG]: Running config-ssh-authkey-fingerprints using lock (<FileLock using file '/var/lib/cloud/instances/i-04e01e659767335ea/sem/config_ssh_authkey_fingerprints'>)
Dec 22 06:53:35 cloud-init[3276]: util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
Dec 22 06:53:35 cloud-init[3276]: util.py[DEBUG]: Read 3957 bytes from /etc/ssh/sshd_config
Dec 22 06:53:35 cloud-init[3276]: util.py[DEBUG]: Reading from /home/ec2-user/.ssh/authorized_keys (quiet=False)
Dec 22 06:53:35 cloud-init[3276]: util.py[DEBUG]: Read 389 bytes from /home/ec2-user/.ssh/authorized_keys
Dec 22 06:53:35 cloud-init[3276]: handlers.py[DEBUG]: finish: modules-final/config-ssh-authkey-fingerprints: SUCCESS: config-ssh-authkey-fingerprints ran successfully
Dec 22 06:53:35 cloud-init[3276]: stages.py[DEBUG]: Running module keys-to-console (<module 'cloudinit.config.cc_keys_to_console' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_keys_to_console.pyc'>) with frequency once-per-instance
Dec 22 06:53:35 cloud-init[3276]: handlers.py[DEBUG]: start: modules-final/config-keys-to-console: running config-keys-to-console with frequency once-per-instance
Dec 22 06:53:35 cloud-init[3276]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04e01e659767335ea/sem/config_keys_to_console - wb: [644] 20 bytes
Dec 22 06:53:35 cloud-init[3276]: helpers.py[DEBUG]: Running config-keys-to-console using lock (<FileLock using file '/var/lib/cloud/instances/i-04e01e659767335ea/sem/config_keys_to_console'>)
Dec 22 06:53:35 cloud-init[3276]: util.py[DEBUG]: Running command ['/usr/libexec/cloud-init/write-ssh-key-fingerprints', '', 'ssh-dss'] with allowed return codes [0] (shell=False, capture=True)
Dec 22 06:53:36 cloud-init[3276]: handlers.py[DEBUG]: finish: modules-final/config-keys-to-console: SUCCESS: config-keys-to-console ran successfully
Dec 22 06:53:36 cloud-init[3276]: stages.py[DEBUG]: Running module phone-home (<module 'cloudinit.config.cc_phone_home' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_phone_home.pyc'>) with frequency once-per-instance
Dec 22 06:53:36 cloud-init[3276]: handlers.py[DEBUG]: start: modules-final/config-phone-home: running config-phone-home with frequency once-per-instance
Dec 22 06:53:36 cloud-init[3276]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04e01e659767335ea/sem/config_phone_home - wb: [644] 20 bytes
Dec 22 06:53:36 cloud-init[3276]: helpers.py[DEBUG]: Running config-phone-home using lock (<FileLock using file '/var/lib/cloud/instances/i-04e01e659767335ea/sem/config_phone_home'>)
Dec 22 06:53:36 cloud-init[3276]: cc_phone_home.py[DEBUG]: Skipping module named phone-home, no 'phone_home' configuration found
Dec 22 06:53:36 cloud-init[3276]: handlers.py[DEBUG]: finish: modules-final/config-phone-home: SUCCESS: config-phone-home ran successfully
Dec 22 06:53:36 cloud-init[3276]: stages.py[DEBUG]: Running module final-message (<module 'cloudinit.config.cc_final_message' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_final_message.pyc'>) with frequency always
Dec 22 06:53:36 cloud-init[3276]: handlers.py[DEBUG]: start: modules-final/config-final-message: running config-final-message with frequency always
Dec 22 06:53:36 cloud-init[3276]: helpers.py[DEBUG]: Running config-final-message using lock (<cloudinit.helpers.DummyLock object at 0x7f88898d8fd0>)
Dec 22 06:53:36 cloud-init[3276]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
Dec 22 06:53:36 cloud-init[3276]: util.py[DEBUG]: Read 14 bytes from /proc/uptime
Dec 22 06:53:36 cloud-init[3276]: util.py[DEBUG]: Cloud-init v. 19.3-3.amzn2 finished at Tue, 22 Dec 2020 06:53:36 +0000. Datasource DataSourceEc2.  Up 184.50 seconds
Dec 22 06:53:36 cloud-init[3276]: util.py[DEBUG]: Writing to /var/lib/cloud/instance/boot-finished - wb: [644] 59 bytes
Dec 22 06:53:36 cloud-init[3276]: handlers.py[DEBUG]: finish: modules-final/config-final-message: SUCCESS: config-final-message ran successfully
Dec 22 06:53:36 cloud-init[3276]: stages.py[DEBUG]: Running module power-state-change (<module 'cloudinit.config.cc_power_state_change' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_power_state_change.pyc'>) with frequency once-per-instance
Dec 22 06:53:36 cloud-init[3276]: handlers.py[DEBUG]: start: modules-final/config-power-state-change: running config-power-state-change with frequency once-per-instance
Dec 22 06:53:36 cloud-init[3276]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-04e01e659767335ea/sem/config_power_state_change - wb: [644] 20 bytes
Dec 22 06:53:36 cloud-init[3276]: helpers.py[DEBUG]: Running config-power-state-change using lock (<FileLock using file '/var/lib/cloud/instances/i-04e01e659767335ea/sem/config_power_state_change'>)
Dec 22 06:53:36 cloud-init[3276]: cc_power_state_change.py[DEBUG]: no power_state provided. doing nothing
Dec 22 06:53:36 cloud-init[3276]: handlers.py[DEBUG]: finish: modules-final/config-power-state-change: SUCCESS: config-power-state-change ran successfully
Dec 22 06:53:36 cloud-init[3276]: main.py[DEBUG]: Ran 9 modules with 1 failures
Dec 22 06:53:36 cloud-init[3276]: atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpd1IWnP) - w: [644] 668 bytes/chars
Dec 22 06:53:36 cloud-init[3276]: atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/result.json (via temporary file /var/lib/cloud/data/tmpVY2KSt) - w: [644] 153 bytes/chars
Dec 22 06:53:36 cloud-init[3276]: util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/result.json' => '../../var/lib/cloud/data/result.json'
Dec 22 06:53:36 cloud-init[3276]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
Dec 22 06:53:36 cloud-init[3276]: util.py[DEBUG]: Read 14 bytes from /proc/uptime
Dec 22 06:53:36 cloud-init[3276]: util.py[DEBUG]: cloud-init mode 'modules' took 121.772 seconds (121.77)
Dec 22 06:53:36 cloud-init[3276]: handlers.py[DEBUG]: finish: modules-final: FAIL: running modules for final
